language: python
dist: xenial

python:
  - "3.6"
  - "3.7"

cache: pip
# command to install dependencies
env:
  - TEST_FILE=tests/labeling/ COVERALLS_PARALLEL=true
  - TEST_FILE=tests/test_corpus.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/test_classification.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/test_custom_multi_output_classification.py COVERALLS_PARALLEL=true
  # Embedding
  - TEST_FILE=tests/embedding/test_bert_embedding.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/embedding/test_gpt2_embedding.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/embedding/test_numeric_features_embedding.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/embedding/test_stacked_embedding.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/embedding/test_bare_embedding.py COVERALLS_PARALLEL=true
  - TEST_FILE=tests/embedding/test_word_embedding.py COVERALLS_PARALLEL=true
  # Labeling
  #  - TEST_FILE=tests/labeling/test_blstm_model.py
  #  - TEST_FILE=tests/labeling/test_cnn_lstm_model.py
  #  - TEST_FILE=tests/labeling/test_seq_self_attenion_model.py
  #  - TEST_FILE=tests/labeling/test_blstm_crf_model.py
  - TEST_FILE=tests/test_processor.py COVERALLS_PARALLEL=true

before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install jieba
  - pip install python-coveralls
  - pip install -e .
  - pip install tensorflow==1.13.1
  - pip install coverage
  - pip install nose
  - pip install pytest pytest-cov
  - pip install flake8 flake8-builtins
  - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"

addons:
  sonarcloud:
    organization: "brikerman-github"
    token:
      secure: $SONAR_TOKEN

script:
  - git fetch --unshallow --quiet
  - flake8 kashgari
  - nosetests --with-coverage --cover-html --cover-html-dir=htmlcov --cover-xml --cover-xml-file=coverage.xml --with-xunit --cover-package="kashgari" $TEST_FILE

after_script:
  - sonar-scanner

notifications:
  webhooks: https://coveralls.io/webhook