language: python
dist: xenial

python:
  - "3.6"
  - "3.7"

cache: pip
# command to install dependencies
env:
  - TEST_FILE=tests/test_corpus.py
  - TEST_FILE=tests/test_classification.py
  - TEST_FILE=tests/test_custom_multi_output_classification.py
  - TEST_FILE=tests/test_embeddings.py
  - TEST_FILE=tests/test_labeling.py
  - TEST_FILE=tests/test_processor.py

before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install jieba
  - pip install python-coveralls
  - pip install -e .
  - pip install tensorflow==1.13.1
  - pip install coverage
  - pip install nose
  - pip install pytest pytest-cov
  - pip install flake8 flake8-builtins
  - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"

addons:
  sonarcloud:
    organization: "brikerman-github"
    token:
      secure: $SONAR_TOKEN

script:
  - git fetch --unshallow --quiet
  - flake8 kashgari
  - nosetests --with-coverage --cover-html --cover-html-dir=htmlcov --cover-xml --cover-xml-file=coverage.xml --with-xunit --cover-package="kashgari" $TEST_FILE
