language: python

python:
  - "3.6"
cache: pip
# command to install dependencies
env:
  - TEST_FILE=tests/test_corpus.py
  - TEST_FILE=tests/test_pre_processor.py
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install jieba
  - pip install python-coveralls
  - pip install .
  - pip install tensorflow==1.13.1
  - pip install coverage
  - pip install nose
# command to run tests
script:
  - nosetests --with-coverage --cover-html --cover-html-dir=htmlcov --cover-package="kashgari" $TEST_FILE
after_success:
  - coveralls
