dist: xenial
#language: python            # this works for Linux but is an error on macOS or Windows

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7

    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7

    - name: "Python 3.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

cache: pip
# command to install dependencies
env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    # Labeling
    - TEST_FILE=tests/labeling/
    #  - TEST_FILE=tests/labeling/test_blstm_model.py
    #  - TEST_FILE=tests/labeling/test_cnn_lstm_model.py
    #  - TEST_FILE=tests/labeling/test_seq_self_attenion_model.py
    #  - TEST_FILE=tests/labeling/test_blstm_crf_model.py
    - TEST_FILE=tests/classification
    - TEST_FILE="tests/test_callbacks.py tests/test_corpus.py tests/test_processor.py"
    - TEST_FILE=tests/test_custom_multi_output_classification.py
    # Embedding
    - TEST_FILE=tests/embedding/
#    - TEST_FILE=tests/embedding/test_bert_embedding.py
#    - TEST_FILE=tests/embedding/test_gpt2_embedding.py
#    - TEST_FILE=tests/embedding/test_numeric_features_embedding.py
#    - TEST_FILE=tests/embedding/test_stacked_embedding.py
#    - TEST_FILE=tests/embedding/test_bare_embedding.py
#    - TEST_FILE=tests/embedding/test_word_embedding.py

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip3 install --upgrade pip
  - pip install jieba
  - pip install python-coveralls
  - pip install -e .
  - pip install tensorflow==1.13.1
  - pip install coverage
  - pip install nose
  - pip install pytest pytest-cov
  - pip install flake8 flake8-builtins
  - python -c "import kashgari;print(f'kashgari version {kashgari.__version__}')"

addons:
  sonarcloud:
    organization: "brikerman-github"
    token:
      secure: $SONAR_TOKEN

script:
  - git fetch --unshallow --quiet
  - flake8 kashgari
  - nosetests --with-coverage --cover-html --cover-html-dir=htmlcov --cover-xml --cover-xml-file=coverage.xml --with-xunit --cover-package="kashgari" $TEST_FILE

after_script:
  - sonar-scanner
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook