# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- develop
- tf.keras-version

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install jieba
    pip install python-coveralls
    pip install .
    pip install tensorflow==1.13.1
    pip install coverage
    pip install nose
    export KASHGARI_PROJECT_DIR=`pwd`
  displayName: 'Install dependencies'

- script: |
    - script: |
    echo $KASHGARI_PROJECT_DIR
    pip install pytest pytest-azurepipelines pytest-cov
    pytest tests/ --cov kashgari --cov-report html
  displayName: 'pytest'